# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0006_auto_20170312_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
