# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0007_paciente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='assistentesocial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='avaliacaopsiquiatrica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='entregadedocumentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fisioterapeuta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='psicologa',
            field=models.BooleanField(default=False),
        ),
    ]
