# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0008_auto_20170312_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='terapeutaocupacional',
            field=models.BooleanField(default=False),
        ),
    ]
