# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-12 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0010_auto_20170312_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='assistentesocial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='avaliacaopsiquiatrica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='entregadedocumentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fisioterapeuta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='psicologa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='terapeutaocupacional',
            field=models.BooleanField(default=False),
        ),
    ]
