# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0011_auto_20170312_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='psicoterapeuta',
            field=models.BooleanField(default=False),
        ),
    ]
