# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0012_paciente_psicoterapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nomeresponsavel',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
