# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0016_auto_20170321_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
