# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0018_auto_20170321_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dataemissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fls',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fone',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fonefixo',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='livro',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pontoreferencia',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='termo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
