# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0019_auto_20170321_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasemana', models.IntegerField()),
                ('periodo', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino')])),
                ('horainicio', models.TimeField()),
                ('horafim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(choices=[('psiq', 'Psiquiatra'), ('psic', 'Psicólogo(a)'), ('enferm', 'Enfermeiro(a)'), ('psicoterap', 'Psicoterapeuta'), ('assissoc', 'Assistente social'), ('fisioterap', 'Fisioterapeuta'), ('terapocup', 'Terapeuta ocupacional')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.Profissional'),
        ),
    ]
