# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0021_auto_20170321_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='validadefim',
            field=models.DateField(default=datetime.datetime(2017, 3, 21, 22, 36, 11, 994055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='horario',
            name='validadeinicio',
            field=models.DateField(default=datetime.datetime(2017, 3, 21, 22, 36, 11, 994030, tzinfo=utc)),
        ),
    ]
