# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0022_auto_20170321_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='diasemana',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='horafim',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='horainicio',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='periodo',
        ),
        migrations.AddField(
            model_name='horario',
            name='horafimM',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='horafimT',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='horainicioM',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='horainicioT',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='quartaM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='quartaT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='quintaM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='quintaT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='segundaM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='segundaT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='sextaM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='sextaT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='tercaM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='tercaT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horario',
            name='validadefim',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='validadeinicio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
