# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0023_auto_20170322_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='profissional',
            name='quantmaxconsulta',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='validadefim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='validadeinicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.Profissional'),
        ),
    ]
