# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0025_auto_20170325_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
    ]
