# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0026_profissional_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='periodo',
            field=models.CharField(blank=True, choices=[('mat', 'Matutino'), ('ves', 'Vespertino')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(),
        ),
    ]
