# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0027_auto_20170410_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(blank=True, choices=[('des', 'Desistir'), ('rem', 'Remarcar'), ('falt', 'Faltou'), ('conc', 'Concluído')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(choices=[('psiq', 'Psiquiatra'), ('psic', 'Psicólogo(a)'), ('enferm', 'Enfermeiro(a)'), ('psicoterap', 'Psicoterapeuta'), ('assissoc', 'Assistente social'), ('fisioterap', 'Fisioterapeuta'), ('terapocup', 'Terapeuta ocupacional'), ('clinico', 'Clínico Geral')], max_length=255),
        ),
    ]
