# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0028_auto_20170501_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='anotacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(blank=True, choices=[('pend', 'Pendente'), ('des', 'Desistir'), ('rem', 'Remarcar'), ('falt', 'Faltou'), ('conc', 'Concluído')], default='pend', max_length=50, null=True),
        ),
    ]
