# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0029_auto_20170501_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caps.Horario'),
        ),
    ]
