# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0030_consulta_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nprontuario',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
