# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0031_paciente_nprontuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='psicoterapeuta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='terapeutaocupacional',
        ),
    ]
